### ISSUE TITLE
Allow posting transactions for previously completed orders [Backend API]

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#124]
In order to support transaction backfilling #76, we need to create a some sort of interface which can post transactions to TaxJar for orders that took place before the reporting feature was enabled.

This is the backend work required to support a frontend UI which can "sync" old transactions to TaxJar  #125 

## Acceptance Criteria

1. If a transaction is already synced to TaxJar, according to our local database
    1. Check if the order totals on TaxJar match the existing transaction #106  
        * [ ] if they do, do nothing
        * [ ] If they don't, update the transaction #112 
            * [ ] If a 404 not found error is encountered, post a new transaction with the info from the local database
2. If a transaction has not been synced to TaxJar, according to our local database
    * [ ] Post the transaction to TaxJar with the default transaction-id
        - [ ] If a 422 already exists error is encountered, update the transaction #112 
* [ ] Only post completed orders that match the criteria for posting a transaction, i.e. when a shipment has been shipped and we are liable #90 
* [ ] Use the `completed_at` date of the order as the transaction date for new transactions, as this will match existing application behavior

**Comment by Noah-Silvera** [comment]
Here are the relevant certification guidelines for reference https://developers.taxjar.com/integrations/sales-tax-reporting/#section-backfilling-transactions

**Comment by Noah-Silvera** [comment]
I reopened this because I'm not positive all the acceptance criteria have been met

**Comment by forkata** [comment]
@Noah-Silvera can we call this done?

**Comment by Noah-Silvera** [comment]
@forkata yeaup!
